@echo off
echo [1/3] Starting backend server...
start /b cmd /c "node server\index.js"
echo [2/3] Starting frontend dev server...
start /b cmd /c "cd client && npm run dev"
echo [3/3] Waiting for services to be ready (8 seconds)...
timeout /t 8 /nobreak >nul
echo Starting Electron...
electron .
